export const AUTH = {
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	SET_CURRENT_USER: 'SET_CURRENT_USER'
}

export const DRAWER = {
    DRAWER_OPEN: 'DRAWER_OPEN',
    DRAWER_CLOSED: 'DRAWER_CLOSED'
}

export const INIT = {
	INIT: 'INIT'
} 